feat/tup-635: Add header demo to core-styles
TACC/Core-Styles pull request #258
Opened 2023-11-09 19:34 UTC by R-Tomas-Gonzalez

## Overview

Feature to create header demo in core-styles.

## Related

- [TUP-635](https://jira.tacc.utexas.edu/browse/TUP-635)

## Changes

Creating demo for header.

## Testing

- Check for any structural or architectural changes recommendations.
- The search bar does not appear on the header.

http://localhost:3000/components/detail/s-header--default
http://localhost:3000/components/detail/s-header--without-branding

## UI

| web | mobile |
| --- | --- |
| <img width="2321" alt="Screenshot 2023-11-09 at 1 29 34 PM" src="https://github.com/TACC/Core-Styles/assets/63771558/01f6313c-1086-4532-89de-a0dd7312f391"> | <img width="878" alt="Screenshot 2023-11-09 at 1 29 48 PM" src="https://github.com/TACC/Core-Styles/assets/63771558/b70940fb-16e1-4cda-b8df-03a1d7d43f5b"> | 
| <img width="2317" alt="Screenshot 2023-11-09 at 1 29 25 PM" src="https://github.com/TACC/Core-Styles/assets/63771558/446c18d4-49e2-498a-8fc8-9893dbc39d32"> | <img width="874" alt="Screenshot 2023-11-09 at 1 29 55 PM" src="https://github.com/TACC/Core-Styles/assets/63771558/63a88c9f-0eed-4d6d-ac8a-5b8e0436795f"> |

## Notes

Please check for search bar in header. Currently does not have it.

2023-11-09 23:59 UTC, wesleyboar requested changes
This is excellent to finally have in the demo!

Glad you got it working. Clean up time.

2023-11-09 23:59 UTC, wesleyboar commented on src/lib/_imports/trumps/_s-portal-nav/_s-portal-nav.hbs
> +  </style>
We found these styles to apparently be necessary. But they are messy (my fault, unmaintained). Please move them to `s-portal-nav.css` and use the same `font-size` and `vertical-align` for both icons (whichever value makes the icon size and alignment look good). That should also allow you to reduce the amount of code. No need to retain the comments.

2023-11-09 23:59 UTC, wesleyboar commented on src/lib/_imports/trumps/_s-portal-nav/_s-portal-nav.hbs
> +    <nav class="dropdown-menu dropdown-menu-right">
Haha! Silly manual class. Thanks for this fix.

2023-11-09 23:59 UTC, wesleyboar commented on src/lib/_imports/trumps/s-header/readme.md
If this will be empty[^1], just delete it.

[^1]: I don't know what to put in here. Not having it is fine with me.

2023-11-09 23:59 UTC, wesleyboar commented on src/lib/_imports/trumps/s-header/s-header--without-branding.hbs
I see this code twice. I know why. Please try to use the import syntax `{{> @blah}}` to allow you to not need to duplicate this. Step one is likely to create a `_s-header--branding.hbs` with just the branding header markup in it.

2023-11-10 18:06 UTC, R-Tomas-Gonzalez commented on src/lib/_imports/trumps/s-header/config.yml
@wesleyboar Did I create this properly? Made changes to reflect https://github.com/TACC/Core-Styles/pull/258#discussion_r1388715232. Please let me know if that's correct.

2023-11-10 20:40 UTC, wesleyboar approved these changes
Great!

2023-11-10 20:40 UTC, merged