task/tup-534 Adds in media query for tables
TACC/Core-Styles pull request #275
Opened 2023-11-28 23:20 UTC by R-Tomas-Gonzalez

## Overview

…

## Related

…

## Changes

…

## Testing

1.

## UI

…

2023-11-29 18:13 UTC, wesleyboar reviewed
Pre-review review 😅.

2023-11-29 20:13 UTC, R-Tomas-Gonzalez commented on src/lib/_imports/elements/html-elements.cms.css
> +)) {
Sounds good to me!

2023-11-29 20:14 UTC, R-Tomas-Gonzalez commented on src/lib/_imports/elements/table--basic.css
> -}
💯🫡

2023-11-29 20:38 UTC, wesleyboar commented on src/lib/_imports/elements/html-elements.cms.css
> +)) {
Resolution:
- #276

2023-12-07 22:52 UTC, R-Tomas-Gonzalez commented
[b440a77](https://github.com/TACC/Core-Styles/pull/275/commits/b440a77b6d4dbc75d17cda314cf3a4776df52b27)

Makes these adjustments:
1. **IMPORTANT**:
- [ ]  On all sizes, increase spacing e.g. `--cell-pad-vert`, `--cell-pad-horz`, line-spacing.
- [ ] On "mobile design", increase spacing even more.

2. **IMPORTANT**: On "mobile design" and smaller, use larger font.

- [ ] Done?

3. **DOUBLE CHECK**: Verify that top border and bottom border on tables mobile and desktop match their status on `main` branch (dev.tup) and are consistent.
- [ ]  If borders are inconsistent on `task/tup-534` branch, that might be a new bug. Check `main`.
- [ ] If borders are inconsistent on `main` branch, that's a `main` branch bug you may fix in `task/tup-534`.

4. **NICE TO HAVE**: On "mobile design" (on desktop), can hovering over column name create a tooltip (without JavaScript). I.e. use `title` attribute as tooltip.
	- **Wes** thinks, "Probably not."

**Tomas:** Did not try this. Will worry about "Nice To Haves" when we have working code.

2023-12-08 19:49 UTC, R-Tomas-Gonzalez commented
[396b40d](https://github.com/TACC/Core-Styles/pull/275/commits/396b40d1254053da06e7c762fb13a73682810b99)

Makes the following change. Having portal not truncate was decided [here](https://tacc-team.slack.com/archives/C068NDEFECD/p1701993678096689)
1. **REMEMBER**: Paragraphs should **not** be truncated by default. ~~Portal **may** truncate them, though~~ (Tomas: No longer the case due to commented out code). 
2. Brings back the top border for paragraphs

2023-12-11 19:05 UTC, wesleyboar commented on src/lib/_imports/trumps/s-truncated-table.css
**Error.** This manner of temporarily disabling this causes an error —

```
[build:watch] Building stylesheet(s) to /Users/wbomar/Code/Core-Styles/dist
[build:watch] 
5:3     ⚠  '.s-truncated-table', has not been defined, so it cannot be extended [postcss-extend]
```

— because `…/elements/table.portal.css` `@extend`s `.s-truncated-table`.

I propose commenting out the relevant include and import in `table.portal.css` instead.

2023-12-13 21:06 UTC, wesleyboar requested changes
The result **looks** excellent — just as we expect while we wait for more design instruction. But I know the code to get there is a work in progress. I've left some notes to track the cleanup that can be done.

2023-12-14 22:42 UTC, wesleyboar reviewed
Cool. I'll be back after we receive design to finish off responsive and nested styles.

2023-12-14 22:42 UTC, wesleyboar commented on src/lib/_imports/elements/table.portal.css
**Cruft?** I think this file **AND** `s-truncated-table.css` **AND** imports of them, can be removed now, because [we got approval to "make them both not truncate"](https://tacc-team.slack.com/archives/C068NDEFECD/p1702058244659889?thread_ts=1701993678.096689&cid=C068NDEFECD). Please double check my understanding.

2023-12-14 22:42 UTC, wesleyboar commented on src/lib/_imports/elements/html-elements.cms.css
> +)) {
Resolution PR was merged. Merging `main` ought to result in a change here too. In the event of a conflict, #276 code is the code to keep here.

2023-12-14 22:42 UTC, wesleyboar commented on src/lib/_imports/elements/table--basic.css
> +  border-spacing: 0; /* overwrite Bootstrap */
To revert accidental movement of comment:

```suggestion
  border-collapse: separate; /* overwrite Bootstrap */
  border-spacing: 0;
```

2024-01-25 15:07 UTC, wesleyboar commented on src/lib/_imports/core-styles.docs.css
> +/* @import url("./elements/html-elements.cms.css"); */
Styling lists in tables may be easier to do via new ticket, [CMD-76](https://tacc-main.atlassian.net/browse/CMD-76).

> [!WARNING]
> But commenting out `html-elements.cms.css` cannot be done here.

I'll help find a solution.

2024-01-25 15:12 UTC, wesleyboar requested changes
For approval, please:
* update screenshots
* resolve merge conflicts
* review [commented out `@import` in `core-styles.docs`](https://github.com/TACC/Core-Styles/pull/275#discussion_r1409591969)
    <sup>Just remember what it's about. I'll try to find a quick fix. Suggestions welcome.</sup>

2024-01-25 15:19 UTC, wesleyboar commented on src/lib/_imports/elements/table--basic.css
> +      padding-inline: unset;
Removing the `min-width` is great. It should have some padding, at most the same. Unless design confirmed otherwise.

```suggestion
```

2024-01-25 16:18 UTC, wesleyboar reviewed
**Third bug found. Not a blocker.** Double borders on mobile tables. I have trouble debugging it. _I hope to avoid border removal bandaid solution._

| Basic Table | Paragraph Table |
| - | - |
| <img width="590" alt="basic" src="https://github.com/TACC/Core-Styles/assets/62723358/2b674e69-ec36-4b83-8c1d-75819409578e"> | <img width="590" alt="paragraph" src="https://github.com/TACC/Core-Styles/assets/62723358/f767d85c-3bbd-460f-9352-009d8985b5b6"> |

<details><summary>Details</summary>


In `table--basic.icss`, there is a —

```
/* To add bottom border to rows */
tr:not(:last-of-type) > :is(td, th),
:--s-paragraph-table p:not(:last-of-type) {
  border-bottom-width: var(--global-border-width--normal);
  border-bottom-style: solid;
  border-bottom-color: var(--global-color-primary--light);
}
```

— and a —

```
@media (max-width: 767px) {
  ...

  tr > :is(td, th):not(:last-of-type),
  :--s-paragraph-table p:not(:last-of-type) {
    border-bottom-width: var(--global-border-width--normal);
    border-bottom-style: solid;
    border-bottom-color: var(--global-color-primary--light);
  }

  ...
}
```

Nested tables avoids double borders by selectively removing them. But maybe there is a solution (a set of selectors, and maybe a use of media queries), for basic and paragraph and nested tables, with less code that only applies the borders as needed, so they need not be removed after the fact.

</details>

2024-01-25 18:46 UTC, R-Tomas-Gonzalez commented
> **Third dug found. Not a blocker.** Double borders on mobile tables. I have trouble debugging it. _I hope to avoid border removal bandaid solution._
> 
> Basic Table	Paragraph Table
> <img alt="basic" width="590" src="https://private-user-images.githubusercontent.com/62723358/299732717-2b674e69-ec36-4b83-8c1d-75819409578e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDg1MjIsIm5iZiI6MTcwNjIwODIyMiwicGF0aCI6Ii82MjcyMzM1OC8yOTk3MzI3MTctMmI2NzRlNjktZWMzNi00YjgzLThjMWQtNzU4MTk0MDk1NzhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE4NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4MzQ3OTExMjhiYmI5ZTFlZWM2ZjljZDQ4ODNjYjVkOTBhYTRiYjRkNDg3ZjRkYmRkOGYyMTRlZDAxODU0Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FnYogWbXdKRiTr7NeLlI6WFdohD1oyZfyg41ivS33h0">	<img alt="paragraph" width="590" src="https://private-user-images.githubusercontent.com/62723358/299732719-f767d85c-3bbd-460f-9352-009d8985b5b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyMDg1MjIsIm5iZiI6MTcwNjIwODIyMiwicGF0aCI6Ii82MjcyMzM1OC8yOTk3MzI3MTktZjc2N2Q4NWMtM2JiZC00NjBmLTkzNTItMDA5ZDg5ODViNWI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDE4NDM0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MTk4ODgzYThlZDQ3NWEwN2IzMDkxNjQzMTJlZDE1NzM4OWVkZTc3MTZkMDA4ODMxMzRkNmYzZjE2MDI2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Skv_OfeDU8-ujChG_fnLoBa1uvtq-rREfYuTTodTlUE">
> Details

Let me know if this is a good resolve: 
(Removes the unset in nested--table, and brings it to the scope of the basic--table)

[8fc5c29](https://github.com/TACC/Core-Styles/pull/275/commits/8fc5c29ee92066cce81a40c071a766c6b07af4cd)

2024-01-25 19:13 UTC, wesleyboar commented
> Let me know if this is a good resolve: (Removes the unset in nested--table, and brings it to the scope of the basic--table) 8fc5c29

Yes.

2024-01-25 20:18 UTC, wesleyboar commented
GitHub trying to be smart by closing this PR for me cuz I said "fixed #275" in another PR… Do only what I say, GitHub.

2024-01-25 20:22 UTC, wesleyboar commented on src/lib/_imports/core-styles.docs.css
> +/* @import url("./elements/html-elements.cms.css"); */
My bad. "Fixed" in #303. I undid this change in 82ff433. Let's be done.

2024-01-25 20:26 UTC, wesleyboar commented on src/lib/_imports/core-styles.docs.css
> +/* @import url("./elements/html-elements.cms.css"); */
Screenshots. List is not indented.

<details><summary>Narrow</summary>

| Docs | CMS |
| - | - |
| <img width="960" alt="table basic docs narrow" src="https://github.com/TACC/Core-Styles/assets/62723358/3c701b01-8bc4-4a44-af4a-37bd18b71373"> | <img width="960" alt="table basic cms narrow" src="https://github.com/TACC/Core-Styles/assets/62723358/89f8ed21-5d3b-439d-9b3a-6c31e0c0624b"> |

</details>
<details><summary>Wide</summary>

| Docs | CMS |
| - | - |
| <img width="960" alt="table basic docs wide" src="https://github.com/TACC/Core-Styles/assets/62723358/2b9d80a2-ac8c-4076-970f-cd5835d25bcb"> | <img width="960" alt="table basic cms wide" src="https://github.com/TACC/Core-Styles/assets/62723358/9b15a0fb-e0d4-4573-954f-689bf30fa872"> |

</details>

2024-01-25 20:27 UTC, wesleyboar approved these changes
YES!

2024-01-25 20:27 UTC, merged

2024-03-12 20:21 UTC, wesleyboar commented
Reverted in #313.
Restored in #317.